require 'csv'
 class Setting < ApplicationRecord

  @@speaker_portal_props = [

    # locked might have to be commented out for the file uploads... not sure.
    # They would need a quite different check
    :locked_photo_file,
    :locked_speaker_form_online_url,
    :locked_cv_file,
    :locked_fd_file,
    :locked_first_name,
    :locked_middle_initial,
    :locked_last_name,
    :locked_email,
    :locked_honor_prefix,
    :locked_honor_suffix,
    :locked_company,
    :locked_address1,
    :locked_address2,
    :locked_address3,
    :locked_city,
    :locked_state,
    :locked_country,
    :locked_zip,
    :locked_work_phone,
    :locked_mobile_phone,
    :locked_home_phone,
    :locked_fax,
    :locked_biography,
    :locked_notes,
    :locked_availability_notes,
    :locked_financial_disclosure,
    :locked_fd_tax_id,
    :locked_fd_pay_to,
    :locked_fd_street_address,
    :locked_fd_city,
    :locked_fd_state,
    :locked_fd_zip,
    :locked_facebook_url,
    :locked_linked_in,
    :locked_twitter_url,
    :locked_custom_filter_1,
    :locked_custom_filter_2,
    :locked_custom_filter_3,

    :hide_photo_file,
    :hide_speaker_form_online_url,
    :hide_cv_file,
    :hide_fd_file,
    :hide_first_name,
    :hide_middle_initial,
    :hide_last_name,
    :hide_email,
    :hide_honor_prefix,
    :hide_honor_suffix,
    :hide_company,
    :hide_address1,
    :hide_address2,
    :hide_address3,
    :hide_city,
    :hide_state,
    :hide_country,
    :hide_zip,
    :hide_work_phone,
    :hide_mobile_phone,
    :hide_home_phone,
    :hide_fax,
    :hide_biography,
    :hide_notes,
    :hide_availability_notes,
    :hide_financial_disclosure,
    :hide_fd_tax_id,
    :hide_fd_pay_to,
    :hide_fd_street_address,
    :hide_fd_city,
    :hide_fd_state,
    :hide_fd_zip,
    :hide_facebook_url,
    :hide_linked_in,
    :hide_twitter_url,
    :hide_custom_filter_1,
    :hide_custom_filter_2,
    :hide_custom_filter_3,

    :fields,
    :hide_abstract,
    :hide_learning_objectives,
    :hide_tags,
    :hide_other_tags,
    :hide_keywords,
    :hide_other_keywords,
    :program_types,
    :create_session,
    :speaker_sessions,
    :printable_schedule,
    :total_session,
    :required_abstract,
    :required_learning_objectives,
    :required_tags,
    :required_other_tags,
    :required_keywords,
    :required_other_keywords,
  ]

  @@exhibitor_portal_props = [
    :locked_company_name,
    :locked_description,
    :locked_email,
    :locked_address_line1,
    :locked_address_line2,
    :locked_country,
    :locked_city,
    :locked_state,
    :locked_zip,
    :locked_phone,
    :locked_fax,
    :locked_toll_free,
    :locked_url_web,
    :locked_url_twitter,
    :locked_url_facebook,
    :locked_url_linkedin,
    :locked_url_rss,
    :locked_url_instagram,
    :locked_url_youtube,
    :locked_url_tiktok,
    :locked_contact_name,
    :locked_contact_title,
    :locked_contact_email,
    :locked_contact_name_two,
    :locked_contact_title_two,
    :locked_contact_email_two,
    :locked_contact_mobile_two,
    :locked_message,
	  :locked_logo,

    :hide_company_name,
    :hide_description,
    :hide_email,
    :hide_address_line1,
    :hide_address_line2,
    :hide_country,
    :hide_city,
    :hide_state,
    :hide_zip,
    :hide_phone,
    :hide_fax,
    :hide_toll_free,
    :hide_change_password,
    :hide_url_web,
    :hide_url_twitter,
    :hide_url_facebook,
    :hide_url_linkedin,
    :hide_url_rss,
    :hide_url_instagram,
    :hide_url_youtube,
    :hide_url_tiktok,
    :hide_message_image_upload,
    :contact_name,
    :contact_title,
    :hide_contact_email,
    :hide_contact_name_two,
    :hide_contact_title_two,
    :hide_contact_email_two,
    :hide_contact_mobile_two,
    :hide_logo,
    :hide_message,
    :limit_no_of_staffs,
    :background_color,
    :bottom_nav,
    :window_header,
    :border_radius,
    :lock_enhanced_exhibitor_portal,
    :default_portal_config,
    :duration,
    :date_range,
    :enable_slotbookings,
    :timeslots_booking,
    :timeslots_booking_label,
    :screen_label,
    :exhibitor_chat_label,
    :check_email_domain,

    :hide_staff_title,
    :hide_staff_email,
    :hide_staff_business_phone,
    :hide_staff_mobile_phone,
    :hide_staff_url_twitter,
    :hide_staff_url_facebook,
    :hide_staff_url_linkedin,
    :hide_staff_url_youtube,
    :hide_staff_url_instagram,
    :hide_staff_url_tiktok,
    :hide_staff_biography,
    :hide_staff_interests,
    :hide_staff_get_featured,
    :hide_staff_first_name,
    :hide_staff_last_name,
  ]

  @@attendee_portal_props = [
    :hide_change_password,
    :locked_email,
    :hide_email,
    :first_name,
  ]

  @@video_portal_props = [
    :video_portal,
    :single_page_app,
    :login_with_devise,
    :auto_sign_in,
    :favourites,
    :forgot_password,
    :option_to_skip_survey,
    :full_schedule,
    :ga_key,
    :video_portal_bgcolor,
    :attendee_chat,
    :html_title,
    :dashboard_title,
    :dashboard_slider,
    :help_text,
    :login_text,
    :external_ce_text,
    :internal_ce_text,
    :standby_screen_text,
    :landing,
    :dashboard_heading,
    :dashboard_menu_name,
    :session_menu_name,
    :exhibitor_menu_name,
    :networking_menu_name,
    :notifications_menu_name,
    :survey_menu_name,
    :blog_menu_name,
    :help_menu_name,
    :photo_gallery_menu_name,
    :game_menu_name,
    :on_demand_menu_name,
    :messaging_menu_name,
    :ask_attendee_details,
    :prefer_last_name,
    :sessions_by_date,
    :sessions_by_tag,
    :sessions_by_audience_tag,
    :sessions_by_speaker,
    :sessions_by_my_ce,
    :attendees_by_alphabet,
    :attendees_by_categories,
    :attendees_by_search,
    :exhibitors_by_sponsors,
    :exhibitors_by_alphabet,
    :exhibitors_by_categories,
    :exhibitors_by_search,
    :session_menu_days,
    :on_demand,
    :session_menu_session_tag,
    :session_menu_audience_tag,
    :session_menu_speakers,
    :session_menu_favorites,
    :session_menu_ce,
    :session_menu_search,
    :session_heading_days,
    :session_heading_session_tag,
    :session_heading_audience_tag,
    :session_heading_speakers,
    :session_heading_favorites,
    :session_heading_ce,
    :exhibitor_heading_gallery,
    :exhibitor_heading_letter,
    :exhibitor_heading_alphabet,
    :exhibitor_heading_sponsers,
    :exhibitor_heading_categories,
    :exhibitor_heading_search,
    :session_heading_search,
    :exhibitor_menu_sponser,
    :exhibitor_menu_alphabetically,
    :exhibitor_menu_category,
    :exhibitor_menu_search,
    :attendee_menu_alphabetically,
    :attendee_menu_category,
    :attendee_menu_search,
    :session_info_label,
    :session_speaker_info_label,
    :session_files_label,
    :session_feedback_label,
    :session_qa_label,
    :session_notes_label,
    :session_polling_label,
    :session_claim_ce_label,
    :exhibitor_info_label,
    :exhibitor_misc_label,
    :exhibitor_files_label,
    :exhibitor_notes_label,
    :exhibitor_contact_label,
    :exhibitor_products_label,
    :exhibitor_links_label,
    :exhibitor_messages_label,
    :exhibitor_staffs_label,
    :sessions_search,
    :show_session_codes,
    :show_speaker_names,
    :premium_access,
    :ce_with_survey,
    :nav_dashboard,
    :nav_sessions,
    :nav_exhibitors,
    :nav_exhibitors_simple,
    :nav_exhibitors_alphabet,
    :nav_messages,
    :nav_help,
    :nav_on_demand,
    :nav_photo_gallery,
    :photo_gallery_url,
    :game_url,
    :nav_notifications,
    :nav_event_survey,
    :nav_icons_show,
    :nav_blog,
    :nav_game,
    :nav_booked_slots,
    :booked_slots_menu_name,
    :nav_networking,
    :session_info,
    :speaker_info,
    :session_files,
    :featured_sessions,
    :live_sessions,
    :polling,
    :polling_live,
    :q_a,
    :notes,
    :exhibitor_info,
    :exhibitor_products,
    :exhibitor_files,
    :exhibitor_links,
    :exhibitor_survey,
    :exhibitor_notes,
    :exhibitor_chat,
    :exhibitor_messages,
    :exhibitor_misc,
    :exhibitor_checkin,
    :exhibitor_staffs,
    :attendee_email,
    :attendee_phone,
    :two_factor,
    :banner_enabled,
    :shuffle_banner,
    :q_a_answers,
    :redirect_to_survey,
    :reverse_day_order,
    :standby_screen,
    :start_time,
    :end_time,
    :show_speaker_email,
    :attendees_messaging_option,
    :hide_ondemands_time,
    :keep_accordion_sections_closed,
    :send_ce_after_survey,
    :default_ce_id,
    :enable_switching_timezone,
    :exhibitors_by_alphabetic_card_view,
    :attendees_by_alphabetic_card_view,
    :enable_exhibitor_booth_banner,
    :enable_livestream_banner,
    :attendee_poll,
    :session_video_from_media_files,
    :percentage_video_viewed_for_iattend
  ]

  @@registration_portal_props = [
    :locked_username,
    :locked_password,
    :locked_email,
    :email,
    :username,
    :first_name,
    :last_name,
    :password,
    :honor_prefix,
    :honor_suffix,
    :title,
    :company,
    :biography,
    :business_unit,
    :business_phone,
    :mobile_phone,
    :country,
    :state,
    :city,
    :twitter_url,
    :facebook_url,
    :linked_in,
    :badge_name,
    :required_email,
    :required_username,
    :required_first_name,
    :required_last_name,
    :required_password,
    :required_honor_prefix,
    :required_honor_suffix,
    :required_title,
    :required_company,
    :required_biography,
    :required_business_unit,
    :required_business_phone,
    :required_mobile_phone,
    :required_country,
    :required_state,
    :required_city,
    :required_twitter_url,
    :required_facebook_url,
    :required_linked_in,
    :required_badge_name,
    :email_label,
    :username_label,
    :first_name_label,
    :last_name_label,
    :honor_prefix_label,
    :honor_suffix_label,
    :title_label,
    :company_label,
    :biography_label,
    :business_unit_label,
    :business_phone_label,
    :mobile_phone_label,
    :country_label,
    :state_label,
    :city_label,
    :twitter_url_label,
    :facebook_url_label,
    :linked_in_label,
    :badge_name_label,
    :agenda,
    :speakers,
    :sponsors,
    :exhibitors,
    :hotel_information,
    :closing_date,
    :closing_time,
    :event_details_1,
    :event_details_2,
    :launch_virtual_portal,
    :receipt_attachment,
    :select_tag_title,
    :agenda_info,
    :speakers_info,
    :exhibitors_info,
    :sponsors_info,
    :hotels_info,
    :enable_profile_message_display,
    :message_to_display,
    :gradient_top,
    :gradient_bottom,
    :body_background_color,
    :body_background_image,
    :body_background_position,
    :body_background_size,
    :body_background_repeat,
    :h1_color,
    :h2_color,
    :h3_color,
    :h4_color,
    :twitter_link,
    :facebook_link,
    :instagram_link,
    :skype_link,
    :linkedin_link,
    :dark_bg_theme,
    :reg_button_class,
    :nav_links_color,
    :already_reg_link_color,
    :bold_text,
    :text_shadow,
    :text_shadow_h1,
    :text_shadow_h2,
    :navbar_text_shadow,
    # customized registrtaions
    :reg_banner,
    :reg_main,
    :reg_header_content,
    :reg_header_bg_img,
    :no_of_content_sections,
    :no_of_content_sections_post_reg,
    :column_list,
    :column_list_post_reg,
    :show_header_index_page,
    :show_header_edit_page,
    :show_header_registered_page,
    :show_header_agenda_page,
    :show_header_speaker_page,
    :show_header_exhibitor_page,
    :show_header_sponsor_page,
    :show_header_hotel_info_page,
    :show_footer,
    :reg_form_header,
    :member_information_page_header,
    :successful_modal_page_header,
    :payment_successful_modal_msg,
    :payment_successful_modal_email_msg,
    :payment_info_page_header,
    :payment_term_info,
    :receipt_email,
    :exhibitor_product_cart_page_header,
    :transaction_tax_value,
    :transaction_tax_name,
    :attach_calendar_invite,
    # For now hardcoding the colms and containers
    :reg_section_container1,
    :reg_section_container2,
    :reg_section_container3,
    :reg_section_container4,
    :reg_section_container5,
    :reg_section_container6,
    :reg_section_container7,
    :reg_section_container8,
    :reg_section_container9,
    :reg_section_container10,

    :reg_section_container1_col1,
    :reg_section_container1_col2,
    :reg_section_container1_col3,
    :reg_section_container1_col4,
    :reg_section_container1_col5,

    :reg_section_container2_col1,
    :reg_section_container2_col2,
    :reg_section_container2_col3,
    :reg_section_container2_col4,
    :reg_section_container2_col5,

    :reg_section_container3_col1,
    :reg_section_container3_col2,
    :reg_section_container3_col3,
    :reg_section_container3_col4,
    :reg_section_container3_col5,

    :reg_section_container4_col1,
    :reg_section_container4_col2,
    :reg_section_container4_col3,
    :reg_section_container4_col4,
    :reg_section_container4_col5,

    :reg_section_container5_col1,
    :reg_section_container5_col2,
    :reg_section_container5_col3,
    :reg_section_container5_col4,
    :reg_section_container5_col5,

    :reg_section_container6_col1,
    :reg_section_container6_col2,
    :reg_section_container6_col3,
    :reg_section_container6_col4,
    :reg_section_container6_col5,

    :reg_section_container7_col1,
    :reg_section_container7_col2,
    :reg_section_container7_col3,
    :reg_section_container7_col4,
    :reg_section_container7_col5,

    :reg_section_container8_col1,
    :reg_section_container8_col2,
    :reg_section_container8_col3,
    :reg_section_container8_col4,
    :reg_section_container8_col5,

    :reg_section_container9_col1,
    :reg_section_container9_col2,
    :reg_section_container9_col3,
    :reg_section_container9_col4,
    :reg_section_container9_col5,

    # Post Registration Page containers

    :post_reg_section_container1,
    :post_reg_section_container2,
    :post_reg_section_container3,
    :post_reg_section_container4,
    :post_reg_section_container5,
    :post_reg_section_container6,
    :post_reg_section_container7,
    :post_reg_section_container8,
    :post_reg_section_container9,
    :post_reg_section_container10,

    :post_reg_section_container1_col1,
    :post_reg_section_container1_col2,
    :post_reg_section_container1_col3,
    :post_reg_section_container1_col4,
    :post_reg_section_container1_col5,

    :post_reg_section_container2_col1,
    :post_reg_section_container2_col2,
    :post_reg_section_container2_col3,
    :post_reg_section_container2_col4,
    :post_reg_section_container2_col5,

    :post_reg_section_container3_col1,
    :post_reg_section_container3_col2,
    :post_reg_section_container3_col3,
    :post_reg_section_container3_col4,
    :post_reg_section_container3_col5,

    :post_reg_section_container4_col1,
    :post_reg_section_container4_col2,
    :post_reg_section_container4_col3,
    :post_reg_section_container4_col4,
    :post_reg_section_container4_col5,

    :post_reg_section_container5_col1,
    :post_reg_section_container5_col2,
    :post_reg_section_container5_col3,
    :post_reg_section_container5_col4,
    :post_reg_section_container5_col5,

    :post_reg_section_container6_col1,
    :post_reg_section_container6_col2,
    :post_reg_section_container6_col3,
    :post_reg_section_container6_col4,
    :post_reg_section_container6_col5,

    :post_reg_section_container7_col1,
    :post_reg_section_container7_col2,
    :post_reg_section_container7_col3,
    :post_reg_section_container7_col4,
    :post_reg_section_container7_col5,

    :post_reg_section_container8_col1,
    :post_reg_section_container8_col2,
    :post_reg_section_container8_col3,
    :post_reg_section_container8_col4,
    :post_reg_section_container8_col5,

    :post_reg_section_container9_col1,
    :post_reg_section_container9_col2,
    :post_reg_section_container9_col3,
    :post_reg_section_container9_col4,
    :post_reg_section_container9_col5,

    # Adding styles for each
    :reg_section_container1_style,
    :reg_section_container2_style,
    :reg_section_container3_style,
    :reg_section_container4_style,
    :reg_section_container5_style,
    :reg_section_container6_style,
    :reg_section_container7_style,
    :reg_section_container8_style,
    :reg_section_container9_style,
    :reg_section_container10_style,

    :reg_section_container1_col1_style,
    :reg_section_container1_col2_style,
    :reg_section_container1_col3_style,
    :reg_section_container1_col4_style,
    :reg_section_container1_col5_style,

    :reg_section_container2_col1_style,
    :reg_section_container2_col2_style,
    :reg_section_container2_col3_style,
    :reg_section_container2_col4_style,
    :reg_section_container2_col5_style,

    :reg_section_container3_col1_style,
    :reg_section_container3_col2_style,
    :reg_section_container3_col3_style,
    :reg_section_container3_col4_style,
    :reg_section_container3_col5_style,

    :reg_section_container4_col1_style,
    :reg_section_container4_col2_style,
    :reg_section_container4_col3_style,
    :reg_section_container4_col4_style,
    :reg_section_container4_col5_style,

    :reg_section_container5_col1_style,
    :reg_section_container5_col2_style,
    :reg_section_container5_col3_style,
    :reg_section_container5_col4_style,
    :reg_section_container5_col5_style,

    :reg_section_container6_col1_style,
    :reg_section_container6_col2_style,
    :reg_section_container6_col3_style,
    :reg_section_container6_col4_style,
    :reg_section_container6_col5_style,

    :reg_section_container7_col1_style,
    :reg_section_container7_col2_style,
    :reg_section_container7_col3_style,
    :reg_section_container7_col4_style,
    :reg_section_container7_col5_style,

    :reg_section_container8_col1_style,
    :reg_section_container8_col2_style,
    :reg_section_container8_col3_style,
    :reg_section_container8_col4_style,
    :reg_section_container8_col5_style,

    :reg_section_container9_col1_style,
    :reg_section_container9_col2_style,
    :reg_section_container9_col3_style,
    :reg_section_container9_col4_style,
    :reg_section_container9_col5_style,

    # Post reg styles
    :post_reg_section_container1_style,
    :post_reg_section_container2_style,
    :post_reg_section_container3_style,
    :post_reg_section_container4_style,
    :post_reg_section_container5_style,
    :post_reg_section_container6_style,
    :post_reg_section_container7_style,
    :post_reg_section_container8_style,
    :post_reg_section_container9_style,
    :post_reg_section_container10_style,

    :post_reg_section_container1_col1_style,
    :post_reg_section_container1_col2_style,
    :post_reg_section_container1_col3_style,
    :post_reg_section_container1_col4_style,
    :post_reg_section_container1_col5_style,

    :post_reg_section_container2_col1_style,
    :post_reg_section_container2_col2_style,
    :post_reg_section_container2_col3_style,
    :post_reg_section_container2_col4_style,
    :post_reg_section_container2_col5_style,

    :post_reg_section_container3_col1_style,
    :post_reg_section_container3_col2_style,
    :post_reg_section_container3_col3_style,
    :post_reg_section_container3_col4_style,
    :post_reg_section_container3_col5_style,

    :post_reg_section_container4_col1_style,
    :post_reg_section_container4_col2_style,
    :post_reg_section_container4_col3_style,
    :post_reg_section_container4_col4_style,
    :post_reg_section_container4_col5_style,

    :post_reg_section_container5_col1_style,
    :post_reg_section_container5_col2_style,
    :post_reg_section_container5_col3_style,
    :post_reg_section_container5_col4_style,
    :post_reg_section_container5_col5_style,

    :post_reg_section_container6_col1_style,
    :post_reg_section_container6_col2_style,
    :post_reg_section_container6_col3_style,
    :post_reg_section_container6_col4_style,
    :post_reg_section_container6_col5_style,

    :post_reg_section_container7_col1_style,
    :post_reg_section_container7_col2_style,
    :post_reg_section_container7_col3_style,
    :post_reg_section_container7_col4_style,
    :post_reg_section_container7_col5_style,

    :post_reg_section_container8_col1_style,
    :post_reg_section_container8_col2_style,
    :post_reg_section_container8_col3_style,
    :post_reg_section_container8_col4_style,
    :post_reg_section_container8_col5_style,

    :post_reg_section_container9_col1_style,
    :post_reg_section_container9_col2_style,
    :post_reg_section_container9_col3_style,
    :post_reg_section_container9_col4_style,
    :post_reg_section_container9_col5_style,

    #Payment
    :have_payment_page,
    # :paypal_merchant_id,
    # :paypal_public_key,
    # :paypal_private_key,
    # :paypal_client_id,
    # :paypal_client_secret_key,
    # :paypal_environment,
    :payment_gateway,
    :product_categories,
    :product_categories_ids,
    :registration_category_ids,
    :is_list_view,

    :registration_button_color,
    :hide_banner_bar,
    :text_color,
    :link_color,
    :content_link_color,
    :registration_button_text_color,
  ]

  @@simple_registration_props = [
    :registration_open,
    :simple_registration_heading,
    :simple_registration_subheading,
    :simple_registration_duration,
    :simple_registration_content,
    :attendees_count,
    :simple_registration_heading1,
    :simple_registration_subheading1,
    :simple_registration_duration1,
    :simple_registration_content1,
    :seats_full_message,
    :registration_with_email_confirmation,
    :send_calendar_invite,
    :body_background_color,
    :body_background_image,
    :body_background_position,
    :body_background_size,
    :body_background_repeat,
    :first_name_label,
    :last_name_label,
    :email_label,
    :company_label,
    :title_label,
    :send_attendee_password,
  ]

  @@speaker_registration_props = [
    :registration_open,
    :speaker_registration_heading,
    :speaker_registration_subheading,
    :speaker_registration_duration,
    :speaker_registration_content,
    :speaker_registration_heading1,
    :speaker_post_registration_heading,
    :speaker_post_registration_subheading,
    :speaker_registration_subheading1,
    :speaker_registration_duration1,
    :speaker_registration_content1,
    :registration_with_email_confirmation,
    :body_background_color,
    :body_background_image,
    :body_background_position,
    :body_background_size,
    :body_background_repeat,
    :first_name_label,
    :last_name_label,
    :email_label,
    :company_label,
    :title_label,
    :numeric_password,
  ]

  # Dec 2018 cordova settings addition Edit the csv file to add settings and
  # adjust defaults; more columns can be added as needed to add more complex
  # behaviour CSV read here will return CSV table object with CSV row objects;
  # They act sort of like hashes.  I could also do open, and use a block, which
  # would give finer grained control and may be worth it to auto exclude rows
  # marked to be unused.
  #
  # TODO: Is there any way at all for me to make this not require a server
  # restart?  There are also issues with when we need to remove something from
  # the cms, it gets very tricky. I suppose I could make a one off script that
  # reinitialized this object?  And a one off script that took the name of an
  # unwanted variable as an argument, and cleared it out of existing settings?
  #
  # It's also painful how error prone csv files are to edit. It might be better
  # to switch to a more reliable format, like ods or xlsx.
  #
  # We also have to keep in mind that the name column strings are passed to
  # eval, and so should never ever be configurable or editable by a user.
  #
  # Seems like I don't need to restart to add something, just to remove
  # something. Hmm.

  require 'csv'
  begin
    @@cordova_all_props = CSV.table(
      Rails.root.join( 'cordova_setting_profiles/main.csv' ), :converters => [:all], :skip_blanks =>  true
    )
  rescue
    # if the parser fails on the csv, don't blow up the app.
    puts "AN ERROR OCCURED.........................................."
    @@cordova_all_props = []
  end

  @@cordova_props = [
    :exhibitors_enabled,
    :ce_credits_enabled,
    :iattend_enabled,
    :guest_qa_page_enabled, # button in cordova app; used to be for guest_views page
    :guest_qa_page_webpage_enabled,
    :guest_qa_page_banner_path,
    :guest_qa_page_background_colour,
    :guest_qa_page_title_background_colour,
    :guest_qa_page_question_background_colour,
    :guest_qa_page_question_text_colour,
    :guest_qa_page_title_text_colour,
    :guest_qa_page_google_apis_font,
    :guest_qa_page_font,
    :guest_qa_page_banner_path,
    :guest_qa_page_hide_session_title,
    :guest_qa_page_hide_attendee_name,
    :guest_qa_page_no_questions_header,
    :guest_qa_page_no_questions_content,

    # mutually exclusive options, but that's only enforced
    # by a radio button on the cordova settings page
    :guest_qa_page_use_whitelist_enabled,
    :guest_qa_page_single_question_mode_enabled,
    :guest_qa_page_show_all_questions_mode_enabled,

    # moderator portal settings
    :chat_management,
    :session_video_display,
    :poll_management,
    :add_polls
  ]

  @@guest_view_props = [
    :leaderboard_disabled,
    :leaderboard_show_attendee_code,
    :leaderboard_google_apis_font,
    :leaderboard_background_colour,
    :leaderboard_logo_path,
    :leaderboard_header_text_colour,
    :leaderboard_header_text,
    :leaderboard_table_background_colour_one,
    :leaderboard_table_background_colour_two,
    :leaderboard_table_text_colour,
    :leaderboard_hide_tiebreaker_column,
    :leaderboard_footnote_text

  ]

  @@cms_props = [

    :show_config_page_edit_preset_tags_button,

    :hide_config_page_import_export_row_sessions,
    :hide_config_page_import_export_row_sessions_full,
    :hide_config_page_import_export_row_speakers,
    :hide_config_page_import_export_row_exhibitors,
    :hide_config_page_import_export_row_maps,
    :hide_config_page_import_export_row_attendees,
    :hide_config_page_import_export_row_notifications,
    :hide_config_page_import_export_row_home_buttons,
    :hide_config_page_export_mobile_css,
    :hide_config_page_import_export_row_delete_session_tags,

    :tag_date_loc_meta_data,

    :hide_menu_registrations_header,
    :hide_menu_app_virtual_config_header,
    :hide_menu_sessions,
    :hide_menu_statistics,
    :hide_menu_speakers,
    :hide_menu_rooms,
    :hide_menu_conference_notes,
    :hide_menu_attendees,
    :hide_menu_education_managers,
    :hide_menu_feedback_summary,
    :hide_menu_download_request,
    :hide_menu_maps_rooms_header,
    :hide_menu_game_header,
    :hide_menu_exhibitors,
    :hide_menu_booths,
    :hide_menu_reports_header,
    :hide_menu_settings_header,
    :hide_menu_video_portal_header,
    :hide_menu_general_portal_settings,
    :hide_menu_event_settings,
    :hide_menu_speaker_portal_settings,
    :hide_menu_exhibitor_portal_settings,
    :hide_menu_mobile_app_booleans,
    :hide_menu_qna_page_settings,
    :hide_menu_guest_view_settings,
    :hide_menu_video_portal_booleans,
    :hide_menu_video_portal_styles,
    :hide_menu_video_portal_headings,
    :hide_menu_video_portal_contents,
    :hide_menu_video_portal_images,
    :hide_menu_video_portal_settings,
    :hide_menu_simple_registration_settings,
    :hide_menu_speaker_registration_settings,
    :hide_menu_registration_portal_settings,
    :hide_menu_exhibitor_registration_portal_settings,
    :hide_menu_game_statistics,
    :hide_menu_report_downloads,
    :hide_menu_templates_header,
    :hide_menu_speaker_email_password_template,
    :hide_menu_speaker_numeric_password_template,
    :hide_menu_speaker_email_confirmation_template,
    :hide_menu_attendee_email_password_template,
    :hide_menu_attendee_email_confirmation_template,
    :hide_menu_registration_attendee_email_password_template,
    :hide_menu_registration_attendee_receipt,
    :hide_menu_registration_attendee_email_confirmation_template,
    :hide_menu_ce_certificate_email_template,
    :hide_menu_calendar_invitation_email_template,
    :hide_menu_exhibitor_email_password_template,
    :hide_menu_exhibitor_receipt_template,
    :hide_menu_portal_settings,
    :hide_menu_mobile_and_app_settings,
    :hide_menu_app_game,
    :hide_menu_surveys,
    :hide_menu_polls,
    :hide_menu_session_polls,
    :hide_menu_app_forms,
    :hide_menu_scavenger_hunts,
    :hide_menu_import_export,
    :hide_menu_home_screen_icons_app,
    :hide_menu_home_screen_icons_mobile,
    :hide_menu_banners,
    :hide_menu_event_maps,
    :hide_menu_notifications,
    :hide_menu_portal_messages,
    :hide_menu_speaker_pdfs,
    :hide_menu_room_layouts,
    :show_menu_app_message_threads,
    :hide_menu_flare_photos_link,
    :hide_menu_video_views,
    :hide_menu_ce_certificates,
    :hide_menu_custom_emails,
    :hide_menu_exhibitor_portal_global_configs,
    :hide_menu_event_tickets,
    :hide_menu_attendee_badges,
    :hide_menu_custom_form,
    :hide_menu_attendee_portal_settings,
    :hide_menu_exhibitor_pdfs,

    :hide_exhibitor_index_add_exhibitor_files_to_placeholders,
    :hide_exhibitor_index_booth_owners_multiple_new,
    :hide_exhibitor_index_bulk_set_exhibitors_photos_to_online,

    :hide_attendee_index_multiple_new_for_all,
    :hide_attendee_index_bulk_add_attendee_photos,
    :hide_attendee_index_bulk_set_attendees_photos_to_online,
    :hide_attendee_index_app_message,

    :hide_attendee_table_attendee_photo,
    :hide_attendee_table_attendee_first_name,
    :hide_attendee_table_attendee_last_name,
    :hide_attendee_table_attendee_business_unit,
    :hide_attendee_table_attendee_title,
    :hide_attendee_table_attendee_company,
    :hide_attendee_table_attendee_email,
    :hide_attendee_table_attendee_registration_id,


    :hide_exhibitor_show_page_edit_custom_content,
    :hide_exhibitor_show_page_exhibitor_products,
    :hide_exhibitor_show_page_media_files,

    :hide_speaker_index_bulk_add_speaker_photos,
    :hide_speaker_index_bulk_set_speakers_photos_to_online,

    :hide_session_file_index_select_sessions_to_add_session_files_to,
    :hide_session_file_index_add_session_file_to_all_sessions,
    :hide_session_file_index_finalize_all_sessions_files,
    :hide_session_file_index_select_session_files_to_publish,

    :hide_session_index_add_files_to_placeholders,
    :hide_session_index_bulk_add_session_thumbnails,
    :hide_session_index_select_pdf_date,

    :hide_session_show_page_speakers_button,
    :hide_session_show_page_sponsors_button,
    :hide_session_show_page_session_tags_button,
    :hide_session_show_page_session_files_button,
    :hide_session_show_page_media_files_button,

    :show_session_show_page_audience_tags_button,
    :show_session_show_page_av_requests_button,
    :show_session_show_page_room_layouts_button,
    :show_session_show_page_get_video_url,
    :show_session_show_page_encode_video,
    :show_session_show_page_search_for_encoded_video,
    :show_session_show_page_video_thumbnail,


    :hide_session_form_next_previous_buttons,
    :hide_session_form_session_code,
    :hide_session_form_title,
    :hide_session_form_description,
    :hide_session_form_session_cancelled,
    :hide_session_form_qa_enabled,
    :hide_session_form_is_poster,
    :hide_session_form_sold_out,
    :hide_session_form_wvctv,
    :hide_session_form_embedded_video_url,
    :hide_session_form_thumbnail_event_file,
    :hide_session_form_learning_objective,
    :hide_session_form_video_ipad,
    :hide_session_form_credit_hours,
    :hide_session_form_program_type,
    :hide_session_form_date,
    :hide_session_form_start_at,
    :hide_session_form_end_at,
    :hide_session_form_sessions_speakers,
    :hide_session_form_location_mapping_id,
    :hide_session_form_published,
    :hide_session_form_video_thumbnail,
    :hide_session_form_video_android,
    :hide_session_form_video_ipad,
    :hide_session_form_price,
    :hide_session_form_capacity,
    :hide_session_form_ticketed,
    :hide_session_form_race_approved,
    :hide_session_form_unpublished,
    :hide_session_form_on_demand,

    # all other session columns, previously not
    # part of the form before settings
    :hide_session_form_poster_number,
    :hide_session_form_tag_twitter,
    :hide_session_form_timezone_offset,
    :hide_session_form_record_type,
    :hide_session_form_video_iphone,
    :hide_session_form_video_duration,
    :hide_session_form_track_subtrack,
    :hide_session_form_session_file_urls,
    :hide_session_form_survey_url,
    :hide_session_form_poll_url,
    :hide_session_form_custom_fields,
    :hide_session_form_tags_safeguard,
    :hide_session_form_custom_filter_1,
    :hide_session_form_custom_filter_2,
    :hide_session_form_custom_filter_3,
    :hide_session_form_feedback_enabled,
    :hide_session_form_promotion,
    :hide_session_form_keyword,
    :hide_session_form_premium_access,
    :hide_session_form_video_file_location,
    :hide_session_form_encoded_videos,

    :hide_statistics_page_game,

    :hide_attendee_form_photo_file,
    :hide_attendee_form_online_url,
    :hide_attendee_form_account_code,
    :hide_attendee_form_first_name,
    :hide_attendee_form_last_name,
    :hide_attendee_form_honor_prefix,
    :hide_attendee_form_honor_suffix,
    :hide_attendee_form_business_unit,
    :hide_attendee_form_title,
    :hide_attendee_form_business_phone,
    :hide_attendee_form_mobile_phone,
    :hide_attendee_form_email,
    :hide_attendee_form_company,
    :hide_attendee_form_assignment,
    :hide_attendee_form_custom_filter_1,
    :hide_attendee_form_username,
    :hide_attendee_form_password,
    :hide_attendee_form_authy_id,
    :hide_attendee_form_biography,
    :hide_attendee_form_messaging_opt_out,
    :hide_attendee_form_app_listing_opt_out,
    :hide_attendee_form_game_opt_out,
    :hide_attendee_form_is_demo,

    # all other attendee columns, previously not
    # part of the form before settings
    :hide_attendee_form_country,
    :hide_attendee_form_state,
    :hide_attendee_form_city,
    :hide_attendee_form_notes_email,
    :hide_attendee_form_notes_email_pending,
    :hide_attendee_form_temp_photo_filename,
    :hide_attendee_form_photo_filename,
    :hide_attendee_form_iattend_sessions,
    :hide_attendee_form_validar_url,
    :hide_attendee_form_publish,
    :hide_attendee_form_twitter_url,
    :hide_attendee_form_facebook_url,
    :hide_attendee_form_linked_in,
    :hide_attendee_form_attendee_type_id,
    :hide_attendee_form_first_run_toggle,
    :hide_attendee_form_video_portal_first_run_toggle,
    :hide_attendee_form_custom_filter_2,
    :hide_attendee_form_custom_filter_3,
    :hide_attendee_form_token,
    :hide_attendee_form_tags_safeguard,
    :hide_attendee_form_speaker_biography,
    :hide_attendee_form_travel_info,
    :hide_attendee_form_table_assignment,
    :hide_attendee_form_custom_fields_1,
    :hide_attendee_form_custom_fields_2,
    :hide_attendee_form_custom_fields_3,
    :hide_attendee_form_premium_member,
    :hide_attendee_form_badge_name,

    #Attendee Profile Form, accessed by attendees on the app
    :hide_attendee_profile_form_first_name,
    :hide_attendee_profile_form_last_name,
    :hide_attendee_profile_form_business_unit,
    :hide_attendee_profile_form_title,
    :hide_attendee_profile_form_business_phone,
    :hide_attendee_profile_form_mobile_phone,
    :hide_attendee_profile_form_email,
    :hide_attendee_profile_form_company,
    :hide_attendee_profile_form_twitter_url,
    :hide_attendee_profile_form_facebook_url,
    :hide_attendee_profile_form_linked_in,

    :hide_attendee_profile_form_honor_prefix,
    :hide_attendee_profile_form_honor_suffix,
    :hide_attendee_profile_form_biography,
    :hide_attendee_profile_form_country,
    :hide_attendee_profile_form_state,
    :hide_attendee_profile_form_city,
    :hide_attendee_profile_form_custom_filter_3,
    :hide_attendee_profile_form_custom_fields_1,
    :hide_attendee_profile_form_custom_fields_2,
    :hide_attendee_profile_form_custom_fields_3,

    :hide_speaker_form_first_name,
    :hide_speaker_form_last_name,
    :hide_speaker_form_email,
    :hide_speaker_form_honor_prefix,
    :hide_speaker_form_honor_suffix,
    :hide_speaker_form_title,
    :hide_speaker_form_city,
    :hide_speaker_form_state,
    :hide_speaker_form_country,
    :hide_speaker_form_zip,
    :hide_speaker_form_work_phone,
    :hide_speaker_form_mobile_phone,
    :hide_speaker_form_home_phone,
    :hide_speaker_form_fax,
    :hide_speaker_form_middle_initial,
    :hide_speaker_form_company,
    :hide_speaker_form_address1,
    :hide_speaker_form_address2,
    :hide_speaker_form_address3,
    :hide_speaker_form_fd_tax_id,
    :hide_speaker_form_fd_pay_to,
    :hide_speaker_form_fd_street_address,
    :hide_speaker_form_fd_city,
    :hide_speaker_form_fd_state,
    :hide_speaker_form_fd_zip,
    :hide_speaker_form_biography,
    :hide_speaker_form_notes,
    :hide_speaker_form_availability_notes,
    :hide_speaker_form_financial_disclosure,
    :hide_speaker_form_unpublished,
    :hide_speaker_form_event_file_photo,
    :hide_speaker_form_event_file_cv,
    :hide_speaker_form_online_url,
    :hide_speaker_form_financial_disclosure_section,

    # all other speaker columns, previously not
    # part of the form before settings
    :hide_speaker_form_photo_filename,
    :hide_speaker_form_speaker_code,
    :hide_speaker_form_twitter_url,
    :hide_speaker_form_facebook_url,
    :hide_speaker_form_linked_in,
    :hide_speaker_form_custom_filter_1,
    :hide_speaker_form_custom_filter_2,
    :hide_speaker_form_custom_filter_3,
    :hide_speaker_form_event_file_fd,
    :hide_speaker_form_speaker_type_id,
    :hide_speaker_form_unsubscribed,
    :hide_speaker_form_token,

    :hide_exhibitor_form_logo,
    :hide_exhibitor_form_company_name,
    :hide_exhibitor_form_address_line1,
    :hide_exhibitor_form_address_line2,
    :hide_exhibitor_form_city,
    :hide_exhibitor_form_state,
    :hide_exhibitor_form_zip,
    :hide_exhibitor_form_country,
    :hide_exhibitor_form_phone,
    :hide_exhibitor_form_url_web,
    :hide_exhibitor_form_url_twitter,
    :hide_exhibitor_form_url_facebook,
    :hide_exhibitor_form_url_linkedin,
    :hide_exhibitor_form_url_rss,
    :hide_exhibitor_form_url_instagram,
    :hide_exhibitor_form_url_youtube,
    :hide_exhibitor_form_url_tiktok,
    :hide_exhibitor_form_contact_name,
    :hide_exhibitor_form_email,
    :hide_exhibitor_form_is_sponsor,
    :hide_exhibitor_form_online_url,
    :hide_exhibitor_form_description,
    :hide_exhibitor_form_message,
    :hide_exhibitor_form_portal_logo_file,
    :hide_exhibitor_form_sponsor_type,
    :hide_exhibitor_form_location_mapping_id,

    # all other exhibtior columns, previously not
    # part of the form before settings
    # :hide_exhibitor_form_user_id,
    :hide_exhibitor_form_fax,
    :hide_exhibitor_form_toll_free,
    :hide_exhibitor_form_contact_title,
    :hide_exhibitor_form_contact_email,
    :hide_exhibitor_form_contact_title_two,
    :hide_exhibitor_form_contact_name_two,
    :hide_exhibitor_form_contact_email_two,
    :hide_exhibitor_form_contact_mobile_two,
    :hide_exhibitor_form_toll_free,
    :hide_exhibitor_form_unsubscribed,
    :hide_exhibitor_form_token,
    :hide_exhibitor_form_custom_fields,
    :hide_exhibitor_form_tags_safeguard,
    :hide_exhibitor_form_exhibitor_code,
    :hide_exhibitor_form_unpublished,

    :hide_notification_form_iattend_session_codes_filter,
    :hide_notification_form_pn_filters,
    :hide_notification_form_unpublish_option,
    # deprecated
    # :hide_settings_tab_info,
    # :hide_settings_tab_general_portal_settings,
    # :hide_settings_tab_event_settings,
    # :hide_settings_tab_speaker_portal_settings,
    # :hide_settings_tab_speaker_portal_av_request_items,
    # :hide_settings_tab_speaker_portal_tabs,
    # :hide_settings_tab_speaker_required_data,
    # :hide_settings_tab_exhibitor_portal_settings,
    # :hide_settings_tab_exhibitor_portal_tabs,
    # :hide_settings_tab_mobile_app_booleans,
    # :hide_settings_tab_qna_page_settings,
    # :hide_settings_tab_guest_view_settings,
    # :hide_settings_tab_video_portal_booleans,
    # :hide_settings_tab_video_portal_strings,
    # :hide_settings_tab_video_portal_styles,
    # :hide_settings_tab_video_portal_headings,
    # :hide_settings_tab_video_portal_contents,
    # :hide_settings_tab_video_portal_images,
    # :hide_settings_tab_registration_portal_settings,
    # :hide_settings_tab_simple_registration_settings,


    :hide_reports_view_attendee_email,
    :hide_reports_view_attendee_mobile_phone,
    :hide_reports_view_attendee_business_phone,

    :hide_exhibitor_portal_attendee_email,
    :hide_exhibitor_portal_attendee_mobile_phone,
    :hide_exhibitor_portal_attendee_business_phone,

    # session program feed settings
    :hide_menu_program_feed_header,
    :hide_menu_program_feed_booleans,
    :hide_menu_program_feed_headings,
    # :hide_menu_program_feed_contents,
    :hide_menu_program_feed_styles,

    # Products
    :hide_menu_products_header,
    :hide_menu_product_categories,
    :hide_menu_products,
    :hide_menu_mode_of_payment,
    :hide_menu_product_coupons,
    :hide_menu_attendee_badge_settings,

    # transactions
    :hide_menu_transactions_header,
    :hide_menu_transactions,
    :hide_menu_item_purchases,
    :hide_menu_exhibitor_purchases,
    :hide_menu_webhook_transactions,
    :hide_menu_attendee_purchases,
    :hide_menu_purchases,
  ]

  @@program_feed_props = [
    :program_feed,
    :load_banner_image,
    :enable_search_bar,
    :sessions_by_tag,
    :sessions_by_speaker,
    :sessions_by_audience_tag,
    :program_title,
    :program_heading,
    :program_feed_twelve_hour_format,
    :default_card_view,
    :speakers_order_by_first_name,
    :sessions_by_exhibitor,
    :show_sponsored_exhibitor,
    :show_featured_speaker
  ]

  @@attendee_badge_portal_props = [
    :portal_open,
    :attendee_badge_portal_heading,
    :attendee_badge_portal_subheading,
    :attendee_badge_portal_duration,
    :attendee_badge_portal_content,
    :body_background_color,
    :body_background_image,
    :body_background_position,
    :body_background_size,
    :body_background_repeat,
    :search_attendee_by,
    :badge_format,
    :badge_format_for_attendee,
    :badge_format_for_exhibitor,
    :badge_format_for_speakers,
    :show_badge_search_field_for_attendee,
    :show_badge_search_field_for_exhibitor,
    :show_badge_search_field_for_speaker,
    :allowed_times_to_print_badge,
    :use_pin_for_security,
    :overide_code
  ]

  @@json_props =
    @@video_portal_props +
    @@cms_props          +
    @@cordova_props      +
    @@exhibitor_portal_props +
    @@attendee_portal_props +
    @@registration_portal_props +
    @@simple_registration_props +
    @@speaker_registration_props +
    @@speaker_portal_props +
    @@guest_view_props +
    @@program_feed_props +
    @@attendee_badge_portal_props +
    @@cordova_all_props.map {|r| r[:name] }

  extend SettingFinders

  belongs_to :setting_type
  belongs_to :event
  after_commit :create_mode_of_payment

  serialize :json, JSON

  def copy_to_event event_id
    MonkeySeeMonkeyDo.save_result_copy( MonkeySeeMonkeyDo.copy_model_to_event( schema(event_id) ) )
  end

  def schema new_event_id
    { ids: { event_id: new_event_id }, model: self, columns: :all }
  end
# Not sure about removing this: attr_accessible :#{method_name} form line 715
  def self.serialized_attr_accessor props
    props.each do |method_name|
      eval "
        def #{method_name}
          (self.json || {})['#{method_name}']
        end
        def #{method_name}=(value)
          self.json ||= {}
          self.json['#{method_name}'] = value
        end
      "
    end
  end

  serialized_attr_accessor @@json_props

  # maybe usable?
  # def self.refresh_cordova_props
    # serialized_attr_accessor @@cordova_all_props.map {|r| r[:name] }
    # something to undefine missing props
    # something to remove settings for missing props.
    # hmm
  # end

  # added this as a method in order to enable
  # access to these when determining what fields
  # have values
  def self.json_props
    @@json_props
  end

  def self.cms_props
    @@cms_props
  end

  def self.video_portal_props
    @@video_portal_props
  end

  def self.exhibitor_portal_props
    @@exhibitor_portal_props
  end

  def self.attendee_portal_props
    @@attendee_portal_props
  end

  def self.speaker_portal_props
    @@speaker_portal_props
  end

  def self.cordova_props
    @@cordova_props
  end

  def self.cordova_all_props
    @@cordova_all_props
  end

  def self.guest_view_props
    @@guest_view_props
  end

  def self.default_settings
    user_default_settings || in_memory_default_settings
  end

  def self.user_default_settings
    type_id = SettingType.where(name: 'cms_settings').first.id
    Setting.where(event_id: 0, setting_type_id: type_id).first
  end

  def self.in_memory_default_settings
    type_id = SettingType.where(name: 'cms_settings').first.id
    Setting.new({
      :event_id        => 0,
      :setting_type_id => type_id,

      :tag_date_loc_meta_data => false,

      :hide_menu_registrations_header  => false,
      :hide_menu_app_virtual_config_header=>false,
      :hide_menu_sessions              => false,
      :hide_menu_statistics            => false,
      :hide_menu_speakers              => false,
      :hide_menu_rooms                 => false,
      :hide_menu_conference_notes      => false,
      :hide_menu_attendees             => false,
      :hide_menu_feedback_summary      => false,
      :hide_menu_download_request      => false,
      :hide_menu_maps_rooms_header     => false,
      :hide_menu_game_header           => false,
      :hide_menu_exhibitors            => false,
      :hide_menu_booths                => false,
      :hide_menu_reports_header        => false,
      :hide_menu_surveys               => false,
      :hide_menu_polls                 => false,
      :hide_menu_session_polls         => false,
      :hide_menu_app_forms             => true,
      :hide_menu_import_export         => false,
      :hide_menu_home_screen_icons_app => false,
      :hide_menu_banners               => false,
      :hide_menu_event_maps            => false,
      :hide_menu_notifications         => false,

      :hide_menu_settings_header       => false,
      :hide_menu_video_portal_header   => false,
      :hide_menu_general_portal_settings    => false,
      :hide_menu_event_settings             => false,
      :hide_menu_speaker_portal_settings    => false,
      :hide_menu_exhibitor_portal_settings  => false,
      :hide_menu_mobile_app_booleans        => false,
      :hide_menu_qna_page_settings          => false,
      :hide_menu_guest_view_settings        => false,
      :hide_menu_video_portal_booleans      => false,
      :hide_menu_video_portal_styles        => false,
      :hide_menu_video_portal_headings      => false,
      :hide_menu_video_portal_contents      => false,
      :hide_menu_video_portal_images        => false,
      :hide_menu_simple_registration_settings => false,
      :hide_menu_speaker_registration_settings => false,
      :hide_menu_registration_portal_settings => false,
      :hide_menu_game_statistics        => false,
      :hide_menu_report_downloads       => false,
      :hide_menu_templates_header       => false,
      :hide_menu_speaker_email_password_template => false,
      :hide_menu_speaker_numeric_password_template => false,
      :hide_menu_speaker_email_confirmation_template => false,
      :hide_menu_attendee_email_password_template => false,
      :hide_menu_attendee_email_confirmation_template => false,
      :hide_menu_registration_attendee_email_password_template => false,
      :hide_menu_registration_attendee_receipt => false,
      :hide_menu_registration_attendee_email_confirmation_template => false,
      :hide_menu_ce_certificate_email_template => false,
      :hide_menu_calendar_invitation_email_template => false,
      :hide_menu_exhibitor_email_password_template => false,
      :hide_menu_exhibitor_receipt_template => false,

      :hide_exhibitor_index_add_exhibitor_files_to_placeholders => false,
      :hide_exhibitor_index_booth_owners_multiple_new => false,
      :hide_exhibitor_show_page_edit_custom_content => false,
      :hide_exhibitor_show_page_exhibitor_products => false,
      :hide_exhibitor_show_page_media_files        => false,
      :hide_exhibitor_index_bulk_set_exhibitors_photos_to_online => false,

      :hide_attendee_index_multiple_new_for_all                => false,
      :hide_attendee_index_bulk_add_attendee_photos            => false,
      :hide_attendee_index_bulk_set_attendees_photos_to_online => false,
      :hide_attendee_index_app_message                         => false,

      :hide_attendee_table_attendee_photo                      => true,
      :hide_attendee_table_attendee_first_name                 => false,
      :hide_attendee_table_attendee_last_name                  => false,
      :hide_attendee_table_attendee_business_unit              => false,
      :hide_attendee_table_attendee_title                      => false,
      :hide_attendee_table_attendee_company                    => false,
      :hide_attendee_table_attendee_email                      => false,
      :hide_attendee_table_attendee_registration_id            => false,

      :hide_speaker_index_bulk_add_speaker_photos            => false,
      :hide_speaker_index_bulk_set_speakers_photos_to_online => false,

      :hide_session_index_add_files_to_placeholders   => false,
      :hide_session_index_bulk_add_session_thumbnails => false,
      :hide_session_index_select_pdf_date             => false,

      :hide_session_file_index_select_sessions_to_add_session_files_to => false,
      :hide_session_file_index_add_session_file_to_all_sessions        => false,
      :hide_session_file_index_finalize_all_sessions_files             => false,
      :hide_session_file_index_select_session_files_to_publish         => false,

      :hide_session_show_page_speakers_button      => false,
      :hide_session_show_page_sponsors_button      => false,
      :hide_session_show_page_session_tags_button  => false,
      :hide_session_show_page_session_files_button => false,
      :hide_session_show_page_media_files_button   => false,

      :show_session_show_page_audience_tags_button => false,
      :show_session_show_page_av_requests_button   => false,
      :show_session_show_page_room_layouts_button  => false,
      :show_session_show_page_get_video_url        => false,
      :show_session_show_page_encode_video         => false,
      :show_session_show_page_search_for_encoded_video => false,
      :show_session_show_page_video_thumbnail      => false,

      :hide_session_form_next_previous_buttons => false,
      :hide_session_form_session_code          => false,
      :hide_session_form_title                 => false,
      :hide_session_form_description           => false,
      :hide_session_form_session_cancelled     => false,
      :hide_session_form_qa_enabled            => false,
      :hide_session_form_learning_objective    => false,
      :hide_session_form_credit_hours          => false,
      :hide_session_form_program_type          => false,
      :hide_session_form_date                  => false,
      :hide_session_form_start_at              => false,
      :hide_session_form_end_at                => false,
      :hide_session_form_sessions_speakers     => false,
      :hide_session_form_location_mapping_id   => false,
      :hide_session_form_price                 => false,
      :hide_session_form_capacity              => false,

      :hide_attendee_form_photo_file          => false,
      :hide_attendee_form_online_url          => false,
      :hide_attendee_form_account_code        => false,
      :hide_attendee_form_first_name          => false,
      :hide_attendee_form_last_name           => false,
      :hide_attendee_form_honor_prefix        => false,
      :hide_attendee_form_honor_suffix        => false,
      :hide_attendee_form_business_unit       => false,
      :hide_attendee_form_title               => false,
      :hide_attendee_form_business_phone      => false,
      :hide_attendee_form_mobile_phone        => false,
      :hide_attendee_form_email               => false,
      :hide_attendee_form_company             => false,
      :hide_attendee_form_assignment          => false,
      :hide_attendee_form_custom_filter_1     => false,
      :hide_attendee_form_username            => false,
      :hide_attendee_form_password            => false,
      :hide_attendee_form_biography           => false,
      :hide_attendee_form_messaging_opt_out   => false,
      :hide_attendee_form_app_listing_opt_out => false,

      #attendee profile is access from app by attendees
      :hide_attendee_profile_form_first_name     => false,
      :hide_attendee_profile_form_last_name      => false,
      :hide_attendee_profile_form_business_unit  => false,
      :hide_attendee_profile_form_title          => false,
      :hide_attendee_profile_form_business_phone => false,
      :hide_attendee_profile_form_mobile_phone   => false,
      :hide_attendee_profile_form_email          => false,
      :hide_attendee_profile_form_company        => false,
      :hide_attendee_profile_form_twitter_url    => false,
      :hide_attendee_profile_form_facebook_url   => false,
      :hide_attendee_profile_form_linked_in      => false,

      :hide_speaker_form_first_name       => false,
      :hide_speaker_form_last_name        => false,
      :hide_speaker_form_email            => false,
      :hide_speaker_form_honor_prefix     => false,
      :hide_speaker_form_honor_suffix     => false,
      :hide_speaker_form_title            => false,
      :hide_speaker_form_city             => false,
      :hide_speaker_form_state            => false,
      :hide_speaker_form_country          => false,
      :hide_speaker_form_zip              => false,
      :hide_speaker_form_work_phone       => false,
      :hide_speaker_form_mobile_phone     => false,
      :hide_speaker_form_home_phone       => false,
      :hide_speaker_form_fax              => false,
      :hide_speaker_form_middle_initial   => false,
      :hide_speaker_form_company          => false,
      :hide_speaker_form_address1         => false,
      :hide_speaker_form_address2         => false,
      :hide_speaker_form_address3         => false,
      :hide_speaker_form_biography        => false,
      :hide_speaker_form_event_file_photo => false,
      :hide_speaker_form_availability_notes => false,

      :hide_exhibitor_form_logo                => false,
      :hide_exhibitor_form_company_name        => false,
      :hide_exhibitor_form_address_line1       => false,
      :hide_exhibitor_form_address_line2       => false,
      :hide_exhibitor_form_city                => false,
      :hide_exhibitor_form_state               => false,
      :hide_exhibitor_form_zip                 => false,
      :hide_exhibitor_form_country             => false,
      :hide_exhibitor_form_phone               => false,
      :hide_exhibitor_form_url_web             => false,
      :hide_exhibitor_form_url_twitter         => false,
      :hide_exhibitor_form_url_facebook        => false,
      :hide_exhibitor_form_url_linkedin        => false,
      :hide_exhibitor_form_url_rss             => false,
      :hide_exhibitor_form_url_instagram       => false,
      :hide_exhibitor_form_url_youtube         => false,
      :hide_exhibitor_form_url_tiktok          => false,
      :hide_exhibitor_form_contact_name        => false,
      :hide_exhibitor_form_email               => false,
      :hide_exhibitor_form_is_sponsor          => false,
      :hide_exhibitor_form_online_url          => false,
      :hide_exhibitor_form_description         => false,
      :hide_exhibitor_form_message             => false,
      :hide_exhibitor_form_portal_logo_file    => false,
      :hide_exhibitor_form_sponsor_type        => false,
      :hide_exhibitor_form_location_mapping_id => false,

      :hide_attendee_form_is_demo => false,

      :hide_notification_form_iattend_session_codes_filter => true,
      :hide_notification_form_pn_filters                   => false,
      :hide_notification_form_unpublish_option             => false,
      :hide_config_page_import_export_row_sessions            => false,
      :hide_config_page_import_export_row_sessions_full       => false,
      :hide_config_page_import_export_row_speakers            => false,
      :hide_config_page_import_export_row_exhibitors          => false,
      :hide_config_page_import_export_row_maps                => false,
      :hide_config_page_import_export_row_attendees           => false,
      :hide_config_page_import_export_row_notifications       => false,
      :hide_config_page_import_export_row_home_buttons        => false,
      :hide_config_page_import_export_row_delete_session_tags => false,
      :hide_config_page_export_mobile_css                     => false,

      :hide_reports_view_attendee_email              => false,
      :hide_reports_view_attendee_mobile_phone       => false,
      :hide_reports_view_attendee_business_phone     => false,
      :hide_exhibitor_portal_attendee_email           => false,
      :hide_exhibitor_portal_attendee_mobile_phone    => false,
      :hide_exhibitor_portal_attendee_business_phone  => false
    })
  end

  def create_mode_of_payment
    if self.have_payment_page
      ModeOfPayment.find_or_create_by(name: 'PayPal', event_id: self.event_id)
      ModeOfPayment.find_or_create_by(name: 'Stripe', event_id: self.event_id)
      ModeOfPayment.find_or_create_by(iid: 'affinipay', name: 'Affinipay', event_id: self.event_id)
    end
  end
end
