source 'https://rubygems.org'

gem 'css_parser', '~> 1.9.0'
gem 'curb', '~> 0.9'

gem 'haml', '~>5.2'

# System of oganization for JS that works with asset pipeline
gem 'modulejs-rails', '~> 2.2'

##symlink must be created and point to local gems directory
gem 'j_picker', '0.0.1', path: './vendor/j_picker'

gem 'rails', '~>6.0'

gem 'uglifier', '~> 4.2'
gem 'sass-rails', '~> 6'
gem 'bootsnap', '~> 1.7.5'
gem 'listen', '~> 3'
#gem 'bootstrap-will_paginate' #, '0.0.6'
gem 'bootstrap-will_paginate', '~> 1.0'

gem 'sqlite3-ruby', '~> 1.3', :require => 'sqlite3'
gem 'mysql2', '~> 0.5.3'
#gem 'composite_primary_keys'
gem 'devise', '~>4.8.0'
gem 'cancancan', '~> 3.3.0'
# gem "strong_parameters"
gem 'dalli', '~> 2.7.11'

# google calender
gem 'google-api-client', '~> 0.53.0'
gem "omniauth", "~> 2.0"
gem 'omniauth-google-oauth2', '~> 1.0'
gem 'icalendar', '~> 2.7.1'
gem 'rest-client', '~> 2.0.1'

gem 'prawn', '~> 2.4' # pdf dsl https://github.com/prawnpdf/prawn
gem 'prawn-table', '~> 0.2.2'
# gem 'prawn-forms' #add fillable fields

gem 'savon', '~> 2.12.1'

# gem 'habtm_checkboxes', :git => "git://github.com/jtrupiano/habtm_checkboxes.git"

gem 'remotipart', '~> 1.4.4'
# gem 'rqrcode_png' # qr code generator
gem 'rqrcode_png', git: "https://github.com/DCarper/rqrcode_png.git"
#spreadsheet scripting import gems
gem 'spreadsheet', '~> 1.2.9'
gem 'nokogiri', '~> 1.11'
gem 'builder', '~> 3.1'
gem 'hpricot', '~> 0.8.6'
gem 'oauth', '~> 0.5.6'
gem 'roo', '~> 2.8.3'

gem 'google-spreadsheet-ruby', '~> 0.3.1'
#gem 'rubyzip'
#gem 'rubyzip',  "~> 1.0.0" #bug workaround
gem 'zip-zip', '~> 0.3'
gem 'archive-zip', '~> 0.12'
#gem 'zip' #needed for import scripts, but conflicts with spreadsheet_summary method in session_files_controller.rb

#gem 'fileutils' #need to upgrade ruby version to 2.5 to use this gem now, v0.7 was removed from ruby gems
gem 'rmagick','~> 4.2'
# gem 'jpicker-rails'

gem 'backbone-on-rails', git: "https://github.com/meleyal/backbone-on-rails.git"

gem 'i18n', '>= 1.6', '< 2'

gem 'colorize', '~> 0.8'

# gem 'ckeditor'#, '~>4.6.1'
gem 'ckeditor', '~>4.3'
gem 'aws-sdk', '~> 3.0'
gem 'aws-sdk-v1', '~> 1.67'

# devise 2fa
gem 'devise-two-factor'
gem 'rqrcode'


# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'sqlite3-ruby', :require => 'sqlite3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:

# this depends on having a more recent version of ruby, which then screws up
# other gems... too bad. A little too much work for right now, esp. because it
# could break production
# group :test do
#   gem "spring" # rails preloaded should speed up tests
# end

gem 'thin',  git: "https://github.com/macournoyer/thin.git"
 # this doesn't need to be listed twice
gem 'faye-rails', '~> 2.0.3'
gem 'rack-cors', '~> 1.1'

 group :development, :test do
#   gem 'webrat'
  gem 'rails-erd', '~> 1.6.1'
  gem 'pry'
  gem 'pry-rails'
  # gem 'thin' #, '~>1.6'
  gem 'factory_bot_rails', '~> 6.2.0'

  gem 'rspec-rails'
  gem 'shoulda-matchers', '~> 5.0'
end


gem 'jquery-rails', '~> 4.4'
gem 'jquery-ui-rails', '~> 6'

gem 'axlsx', :git => 'https://github.com/randym/axlsx.git'
#gem 'axlsx', :git => 'git://github.com/randym/axlsx.git'
gem 'axlsx_rails', '~> 0.6'
gem 'authy', '~> 3'

# For email template with bootstrap
gem 'bootstrap-email', '~> 0.3'

gem 'bootstrap-multiselect-rails', '~> 0.9'

# gem 'bootstrap-datepicker-rails'
# gem 'bootstrap-timepicker-rails'
gem 'momentjs-rails', '~> 2.20.1'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.47'
gem 'bootstrap-daterangepicker-rails', '~> 3.0.5', git: 'https://github.com/jordanbrock/bootstrap-daterangepicker-rails.git', branch: 'master'
# gem 'bootstrap4-datetime-picker-rails'

# group :production do
#   gem 'thin' #, '~>1.6'
# end

group :assets do
  #gem 'sass-rails' # #, '~> 3.2.3'
  gem "less-rails", "~> 5.0" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
  gem 'twitter-bootstrap-rails', '~> 3.2'
  gem 'coffee-rails', '~> 5' #, '~> 3.2.1'
end

gem 'sprockets-rails', '~> 3.2'
gem "font-awesome-rails", '~> 4.7'
gem 'bootstrap', '~> 4.0'
gem 'jquery-datatables', '~> 1.10'
gem 'data_migrate', '~> 7.0', '>= 7.0.2'
gem 'pretender'
gem 'sidekiq'
gem 'sidekiq-scheduler', '~> 2.0', '>= 2.0.8'
# gem "braintree"
# gem 'paypal-sdk-rest'
gem 'zebra-zpl'
gem 'stripe'
gem 'recaptcha'
gem 'sidekiq-unique-jobs'
